apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: dummy-repo2
  annotations:
    github.com/project-slug: vmcastillo20/dummy-repo2
spec:
  type: other
  lifecycle: unknown
  owner: guests
